### ISSUE TITLE
Create PreviewParameterProvider class

### ISSUE THREAD

**Issue by HanBI24** [levinzonr/jetpack-compose-ui-arch-plugin#19]
**Choose what area you would us to improve**
- [x] Live templates (Composable functions shortcuts)
- [x] Architecture Templates (Templates for new features and components)
- [ ] Other

**Please describe the feature and/or improvement:**

## Add PreviewParameterProvider into Live template

To create a PreviewParameterProvider, we have to write a lot of code, which is annoying. So, I created a Live template like this:

```xml
<!-- ComposeUiArch.xml -->

'''
    <template
        name="compara" value="@androidx.compose.ui.tooling.preview.PreviewParameterProvider&#10;class $NAME$StatePreviewParameterProvider : PreviewParameterProvider&#60;$NAME$State&#60; {&#10; override val values: Sequence&#60;$NAME$State&#60; = sequenceOf(&#10; &#10; &#10;)&#10;}"
        description="Create a new PreviewParameterProvider"
        toReformat="true"
        toShortenFQNames="true">
        <variable name="NAME" expression="" defaultValue="" alwaysStopAt="true"/>
        <context>
            <option name="com.levinzonr.compose.livetemplate.context" value="true"/>
        </context>
    </template>
```

## Add PreviewParameterProvider into Architecture Templates

Also, I think adding PreviewParameterProvider to Architecture Templates would save a lot of work.
```kotlin
// ComposeContract.kt.ft
import androidx.compose.ui.tooling.preview.PreviewParameterProvider

'''

class ${NAME}StatePreviewParameterProvider : PreviewParameterProvider<${NAME}State> {
    override val values: Sequence<${NAME}State> = sequenceOf(

    )
}
```

However, some users may not want this, so it would be nice to add it as an option, like this.
```kotlin
// AdvancedDialog.kt
group("PreviewParameterProvider") {
                row {
                    checkBox("Use PreviewParameterProvider")
                        .bindSelected(viewModel::usePreviewParameterProvider)
                }
                row { comment("Automatically creates a PreviewParameterProvider.") }
            }
```

Can I try a pr?

**Comment by levinzonr** [comment]
Hey @HanBI24 
This seems pretty useful to me :) 
Feel free to create a PR if you have time, your contribution is highly welcome 👍

**Comment by levinzonr** [comment]
The PR is merged and is new version is pending approval in JetBrains Marketplace :)

**Comment by HanBI24** [comment]
Thank you !!
